---
- hosts: Ubuntu
  become: yes
  tasks:
    - name: install MariaDB Server
    - apt: name=mariadb-server state=lastest
    - name: install MariaDB Client
    - apt: name=mariadb-client state=lastest
  http_port "3306"

- hosts: RedHat
  become: yes
  remote_user: sysadmin
  become_method: sudo
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: install nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
  http_port "80"
  http_port "433"