---
- hosts: RedHat
  become: yes
  remote_user: sysadmin
  become_method: sudo
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

- hosts: ubuntu
  become: yes
  tasks:
    - name: install MariaDB
    - apt: name=mariadb-server state=lastest
